FROM node:6.10

COPY package.json webpack.config.js yarn.lock /code/
COPY public /code/public
COPY src /code/src

RUN mkdir /node_modules && \
    chown -R node:users /code /node_modules

ENV PATH /node_modules/.bin:$PATH
USER node:users
WORKDIR /code

RUN yarn install --modules-dir /node_modules
VOLUME /node_modules
