version: '2'

services:
  db:
    image: mongo:3.4
    networks:
      - backbone
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: carton exec -- morbo server.pl
    environment:
      - DB=mongo://db/library
      - MOJO_LISTEN=http://*:4711
    volumes:
      - ./server.pl:/code/server.pl
      - ./public:/code/public
      - ./cpanfile:/code/cpanfile
      - ./cpanfile.snapshot:/code/cpanfile.snapshot
      - carton:/carton
    ports:
      - "4711:4711"
    networks:
      - backbone
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: yarn run start --modules-folder /node_modules
    environment:
      - BACKEND=http://backend:4711
    volumes:
      - ./package.json:/code/package.json
      - ./webpack.config.js:/code/webpack.config.js
      - ./yarn.lock:/code/yarn.lock
      - ./public:/code/public
      - ./src:/code/src
      - node_modules:/node_modules
    ports:
      - "80:8080"
      - "8080:8080"
    networks:
      - backbone

networks:
  backbone:

volumes:
  carton:
  node_modules:
