FROM perl:5.24

COPY server.pl cpanfile cpanfile.snapshot /code/

RUN cpanm Carton && \
    useradd -m mojo -g users && \
    mkdir /carton && \
    chown -R mojo:users /code /carton

ENV PERL_CARTON_PATH=/carton
USER mojo:users
WORKDIR /code

RUN carton install
VOLUME /carton
