version: '2'

services:
  db:
    image: mongo:3.4
    networks:
      - backbone
  backend:
    build:
      context: ./backend
    command: carton exec -- morbo server.pl
    environment:
      - DB=mongodb://db/library
      - MOJO_LISTEN=http://*:4711
    volumes:
      - ./backend:/code
      - carton:/carton
    ports:
      - "4711:4711"
    networks:
      - backbone
  frontend:
    build:
      context: ./frontend
    command: yarn run start --modules-folder /node_modules
    environment:
      - BACKEND=http://backend:4711
    volumes:
      - ./frontend:/code
      - node_modules:/node_modules
    ports:
      - "80:8080"
      - "8080:8080"
    networks:
      - backbone

networks:
  backbone:

volumes:
  carton:
  node_modules:
